# Generated by Django 5.2.5 on 2025-10-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='ABOUT US', max_length=100)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True)),
                ('quick_links', models.TextField(blank=True, help_text='Label|url per line')),
                ('services_links', models.TextField(blank=True, help_text='Label|url per line')),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=100)),
                ('contact_address', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2025 AKS. All Rights Reserved.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('readmore_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.CharField(default='images/logo-dark.png', max_length=255)),
                ('nav_home', models.CharField(default='Home', max_length=50)),
                ('nav_about', models.CharField(default='About Us', max_length=50)),
                ('nav_services', models.CharField(default='Services', max_length=50)),
                ('nav_gallery', models.CharField(default='Gallery', max_length=50)),
                ('nav_contact', models.CharField(default='Contact Us', max_length=50)),
                ('header_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('header_button_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
